### ISSUE TITLE
Add some color to the site

### ISSUE THREAD

**Issue by rcasto** [rcasto/cupandpen#23]
Am thinking of incorporating styles like the following:
```css
html {
    background-color: <random-color>;
}
body {
    background-color: white;
    padding: 16px;
    border: 1px solid black;
    border-radius: 64px;
}
```

The random color mentioned above would be a standard [CSS named color](https://drafts.csswg.org/css-color/#named-colors) chosen at random.
